### ISSUE TITLE
Add psutil sample

### ISSUE THREAD

**Issue by rdasgupt** [ibm-watson-iot/iot-c#4]
To make it consistent across all bindings, add psutil samples in iot-c

- use a short unique name for the device sample that will be prefixed by "iot" for the device type when used ... e.g. the reference device client is based on psutil for python and we use a `typeId` of `iotsputil`, based on oshi in java and we use a `typeId` of `iotoshi`
  - https://github.com/ibm-watson-iot/iot-java/tree/master/samples/oshi
  - https://github.com/ibm-watson-iot/iot-python/tree/master/samples/psutil
- README should take similar approach as the java and python reference samples
- Event format, as with Java and python should be **slightly** different, so that we can use these as example of the benefits of data normalization across device types ... ensure there is not a 100% match of event format with either existing samples
- Should support connection to quickstart using `--quickstart` argument
- Should display the standard "welcome to quickstart" blurb when connected to quickstart (see psutil for text: https://github.com/ibm-watson-iot/iot-python/blob/be1d749b69f098db22a8bf710124e16fbb770b9c/samples/psutil/src/iotpsutil.py#L107
- Should include a Dockerfile for a dockerized version of the sample, based on alpine image
- Should include a helm chart for deployment to kuberentes
- Helm chart and docker image should be should be compatible with the deviceFactory and we should be able to automate the deployment of this image using that code sample in the same way we have deployed iotpsutil and iotoshi images.  See: https://github.com/ibm-watson-iot/iot-python/tree/master/samples/deviceFactory for more information
- Docker image should be released on docker hub using the short name as the image name (ie without the `iot` prefix we use for device type), under wiotp organization: https://hub.docker.com/u/wiotp
- Helm chart should be released on our chart repo: https://github.com/ibm-watson-iot/ibm-watson-iot.github.io/tree/master/helm

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
