### ISSUE TITLE
Add Managed Device documentation

### ISSUE THREAD

**Issue by rdasgupt** [ibm-watson-iot/iot-c#5]
Document managed device features provided by iot-c client

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
