### ISSUE TITLE
Add Managed Gateway documentation

### ISSUE THREAD

**Issue by rdasgupt** [ibm-watson-iot/iot-c#6]
Add documentation on Managed Gateway features in iot-c client.

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
