### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by astone2014** [ibm-watson-iot/iot-c#7]
I see the library is said to be only built and tested on Linux & OSX but I see dllexports for Windows in the src code. I assume someone has built and tested this to some degree on Windows?

I want the application I create to run on both Windows and Linux gateways.

**Comment by rdasgupt** [comment]
This SDK is not supported on Windows as it is not built and tested on Windows yet.

**Comment by astone2014** [comment]
> This SDK is not supported on Windows as it is not built and tested on Windows yet.

@rdasgupt Are you accepting contributions to this SDK?
I attempted to build the library for Windows and there seems to be only  a few items to take care of.

- Some header files do not exist on Windows. We need some equivalent, not hard.
```C
#include <unistd.h>
#include <libgen.h>
```
- Not allowed to initialize variable length arrays, idk how this works on Linux?
```C
int len = strlen(format) + strlen(commandId) + strlen(formatString) - 3;
char topic[len];
```

paho.mqtt.c is very easy to build for windows using CMAKE.

**Comment by rdasgupt** [comment]
@astone2014 
I have not looked into this repo for a long time. Thanks for your offer to contribute. If you have a build on windows, please submit a PR against develop branch.

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
