### ISSUE TITLE
Static Code analyzer errors

### ISSUE THREAD

**Issue by Pro** [ibm-watson-iot/iot-c#8]
Using the clang scan-build (Version 9) tool, this code has many issues and therefore dependent code on our side inherits these issues.

Could you please fix them?

```bash
sudo apt install clang-tools-9
cd iot-c
mkdir scan-build && cd scan-build
scan-build-9 cmake -DCMAKE_C_COMPILER=/usr/bin/clang-9 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-9 -G "Unix Makefiles" ..
CXX="clang++-9" CC="clang-9" scan-build-9 -enable-checker security.FloatLoopCounter \
          -enable-checker security.insecureAPI.UncheckedReturn \
          --status-bugs -v \
          make -j 8
```

**Comment by durera** [comment]
Unfortunately we will not be able to look into this issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
